"use client";
import {useEffect,useRef,useState} from "react";
import {IconDownload,IconPhotoPlus,IconSlideshow} from "@tabler/icons-react";
import type {Scenic} from "../lib/catalog";
import {validatePhoto} from "../lib/mobile";

type LocalPhoto={id:string;url:string;name:string};
export function MobileJournal({scenic}:{scenic:Scenic}){
  const [photos,setPhotos]=useState<LocalPhoto[]>([]);const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [video,setVideo]=useState("");const [format,setFormat]=useState("webm");const canvas=useRef<HTMLCanvasElement>(null);const animation=useRef(0);const recorder=useRef<MediaRecorder|null>(null);
  const photosRef=useRef<LocalPhoto[]>([]);useEffect(()=>{photosRef.current=photos},[photos]);
  useEffect(()=>()=>{photosRef.current.forEach(item=>URL.revokeObjectURL(item.url));if(video)URL.revokeObjectURL(video);cancelAnimationFrame(animation.current);if(recorder.current?.state==="recording")recorder.current.stop()},[video]);
  function choose(files:FileList|null){if(!files)return;const incoming=Array.from(files).slice(0,8-photos.length);const issue=incoming.map(validatePhoto).find(Boolean);if(issue){setNotice(issue);return}const next=incoming.map(file=>({id:crypto.randomUUID(),url:URL.createObjectURL(file),name:file.name}));setPhotos(value=>[...value,...next]);setSelected(value=>[...value,...next.map(item=>item.id)].slice(0,6));setNotice("照片只在当前浏览器页面中使用，不会上传到服务器。")}
  async function makeVideo(){
    const chosen=selected.map(id=>photos.find(item=>item.id===id)).filter(Boolean) as LocalPhoto[];if(!chosen.length||!canvas.current)return;
    if(typeof MediaRecorder==="undefined"||!canvas.current.captureStream){setNotice("当前浏览器不支持视频导出，请更换支持录屏编码的浏览器。");return}
    const mime=["video/webm;codecs=vp9","video/webm","video/mp4"].find(value=>MediaRecorder.isTypeSupported(value));if(!mime){setNotice("当前浏览器暂不支持视频编码。");return}
    setBusy(true);setNotice("正在读取照片并生成电子相册…");
    try{
      const images=await Promise.all(chosen.map(item=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("照片读取失败，请重新选择。"));image.src=item.url})));
      const c=canvas.current;c.width=720;c.height=960;const ctx=c.getContext("2d");if(!ctx)throw new Error("无法创建视频画面。");const stream=c.captureStream(24);const rec=new MediaRecorder(stream,{mimeType:mime});const chunks:Blob[]=[];recorder.current=rec;
      rec.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};rec.onstop=()=>{stream.getTracks().forEach(track=>track.stop());if(video)URL.revokeObjectURL(video);setVideo(URL.createObjectURL(new Blob(chunks,{type:mime})));setFormat(mime.includes("mp4")?"mp4":"webm");setBusy(false);setNotice("电子相册已生成，可以预览或下载保存。")};;
      const total=images.length*2600,start=performance.now();const draw=(time:number)=>{const elapsed=time-start,index=Math.min(Math.floor(elapsed/2600),images.length-1),image=images[index];ctx.fillStyle="#f7f4e9";ctx.fillRect(0,0,720,960);const scale=Math.max(660/image.width,720/image.height)*(1+(elapsed%2600)/2600*.04);ctx.save();ctx.beginPath();ctx.rect(30,30,660,720);ctx.clip();ctx.drawImage(image,360-image.width*scale/2,390-image.height*scale/2,image.width*scale,image.height*scale);ctx.restore();ctx.fillStyle="#315440";ctx.font="bold 38px sans-serif";ctx.fillText(scenic.name,38,820);ctx.font="22px sans-serif";ctx.fillText("黔小探 · 我们的贵州电子相册",38,869);ctx.fillStyle="#87927c";ctx.font="18px sans-serif";ctx.fillText(`${index+1} / ${images.length}`,38,919);if(elapsed>=total){rec.stop();return}setNotice(`正在生成电子相册 ${Math.min(100,Math.round(elapsed/total*100))}%`);animation.current=requestAnimationFrame(draw)};rec.start();draw(start);
    }catch(error){setBusy(false);setNotice(error instanceof Error?error.message:"制作失败，请重试。")}
  }
  return <section className="m-journal"><div className="m-intro"><span>旅行后 · 电子相册</span><h1>把这一路，变成一段会播放的回忆。</h1><p>选择喜欢的照片，让小探为你自动编排一段旅行相册。</p></div><label className="m-upload-button"><IconPhotoPlus stroke={1.8}/> 上传旅行照片<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy||photos.length>=8} onChange={e=>choose(e.target.files)}/></label><div className="m-album-select">{photos.map(item=><button key={item.id} disabled={busy} className={selected.includes(item.id)?"active":""} onClick={()=>setSelected(value=>value.includes(item.id)?value.filter(id=>id!==item.id):value.length<6?[...value,item.id]:value)}><img src={item.url} alt={item.name}/><span>{selected.includes(item.id)?selected.indexOf(item.id)+1:"＋"}</span></button>)}</div>{!photos.length&&<p className="m-empty">还没有旅行照片，先从设备里选择一张吧。</p>}<p className="m-disclaimer">最多上传 8 张、选择 6 张照片。</p><button className="m-primary" onClick={makeVideo} disabled={busy||!selected.length}><IconSlideshow stroke={1.8}/>{busy?"正在生成…":`一键生成电子相册 · ${selected.length} 张`}</button>{notice&&<p className="m-notice" role="status">{notice}</p>}<canvas ref={canvas} hidden/>{video&&<div className="m-video-result"><video src={video} controls playsInline/><a className="m-secondary" download={`黔小探-${scenic.name}-电子相册.${format}`} href={video}><IconDownload stroke={1.8}/> 下载电子相册视频</a></div>}</section>;
}
